language: java
scala: 2.12.10
os: linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      brew update;
      brew install sbt;
    fi
script: sbt "$SBT_TEST_CMD";

# We explicitly set the matrix to include oraclejdk8 because MacOS X has issues. See comment below
matrix:
  include:
    - jdk: oraclejdk9
      language: scala
      env: SBT_TEST_CMD="^validate"
      # oraclejdk8 is not yet available.
      # see https://github.com/travis-ci/travis-ci/issues/2316
    - os: osx
      env: SBT_VERSION_CMD="^validate ^validateUniversal"
      osx_image: xcode9.4

sudo: false
cache:
 apt: true
 directories:
 - $HOME/.sbt
 - $HOME/.ivy2
