language: java
scala: 2.12.10
os: linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      brew update;
      brew install sbt;
    fi
script: sbt clean test

matrix:
  include:
    - jdk: oraclejdk13
      language: scala
      # oraclejdk8 is not yet available.
      # see https://github.com/travis-ci/travis-ci/issues/2316
    - os: osx
      osx_image: xcode9.4

sudo: false
cache:
 apt: true
 directories:
 - $HOME/.sbt
 - $HOME/.ivy2
