functionality:
  name: "tcomp_multioutput"
  namespace: "viash"
  version: 0.0.1
  description: Test component with multiple output files
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      description: Describe the input file.
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      direction: output
      required: true
      description: Describe the output file.
    - name: "--log"
      alternatives: [ "-l" ]
      type: file
      direction: output
      default: log.txt
      description: Log info.
  resources:
    - type: bash_script
      path: script.sh
    - path: input.txt
platforms:
  - type: docker
    image: ubuntu:20.04
    setup:
      - type: apt
        packages:
          - bash
  - type: nextflow
    publish: true
