functionality:
  name: "tcomp_noinput"
  namespace: "viash"
  version: 0.0.1
  description: Test component without input, only output is generated
  arguments:
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      direction: output
      required: true
      description: Describe the output file.
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: docker
    image: ubuntu:20.04
    setup:
      - type: apt
        packages:
          - bash
  - type: nextflow
    publish: true
