functionality:
  name: "tcomp_multiinput"
  namespace: "viash"
  version: 0.0.1
  description: Testing component for testing multiple inputs in a NXF context
  arguments:
    - name: "--input1"
      type: file
      direction: input
      required: true
    - name: "--input2"
      type: file
      direction: input
      required: true
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      direction: output
      required: true
      description: Describe the output file.
  resources:
    - type: bash_script
      path: script.sh
    - path: input1.txt
    - path: input2.txt
  tests:
    - type: bash_script
      path: test.sh
platforms:
  - type: docker
    image: ubuntu:20.04
    setup:
      - type: apt
        packages:
          - bash
  - type: nextflow
    publish: true
