name: Scala CI
  
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8
    - name: Set up R
      run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y r-base
    - name: Run tests
      run: sbt clean 'testOnly -- -l com.dataintuitive.viash.DockerTest' # exclude docker tests for now
