name: Scala CI
  
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        os: [ ubuntu-latest ] # os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install -y libcurl4-openssl-dev
    - name: Set up Scala
      uses: olafurpg/setup-scala@v5
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8
    - name: Set up R
      uses: r-lib/actions/setup-r@master
      with:
        r-version: '3.6.1'
    - name: Install tidyverse and optparse
      run: Rscript -e "install.packages(c('optparse', 'tidyverse'), repos = 'http://cran.rstudio.com', type = 'source')"
    - name: Run tests on Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: sbt test
    - name: Run tests on macOS
      if: startsWith(matrix.os, 'macOS')
      run: sbt 'testOnly -- -l com.dataintuitive.viash.DockerTest'
